// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNDTZw8Bf9Wc07HX4loC9zKe5ep-R6kmk',
    appId: '1:371413294217:web:afc4484c8163bd5ad6ba58',
    messagingSenderId: '371413294217',
    projectId: 'skinsense-58629',
    authDomain: 'skinsense-58629.firebaseapp.com',
    storageBucket: 'skinsense-58629.firebasestorage.app',
    measurementId: 'G-FDHJDY153T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0KMcJ5q3hFLp-nHZAiqvWOjTFSN3ceY',
    appId: '1:371413294217:android:0055b97b6f0d18fbd6ba58',
    messagingSenderId: '371413294217',
    projectId: 'skinsense-58629',
    storageBucket: 'skinsense-58629.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh1RJyQ-Gh0VlPrIUlAttczdUU7-L7LZs',
    appId: '1:371413294217:ios:201ae2d0a5c55420d6ba58',
    messagingSenderId: '371413294217',
    projectId: 'skinsense-58629',
    storageBucket: 'skinsense-58629.firebasestorage.app',
    iosClientId: '371413294217-tm178k9fbs3mrt3l2ji6tgt845lrd4n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinsense1',
  );

}